### ISSUE TITLE
Pass settings to custom property editor

### ISSUE THREAD

**Issue by themaf** [ben-mckernan/react-to-dijit-adapter#1]
I'm working on a custom property editor for our Episerver site. This adapter has been a great help, I'm new to both dojo and react, and I couldn't get my property editor to work without it.

But the issue I have now is that I would like to pass settings from the property to the react component. I'm building a new editor for existing tag properties that we have on the site today and we have some cases where only one tag is allowed and other where more than one is ok, as well as cases where we would allow new tags to be created and cases where we only want users to be able to choose from existing tags. 

Today we use attributes on the property to pass settings along to the tag-editor, and ideally it would work the same with this new editor I'm building, but this doesn't seem to be possible with this adapter as far as I can tell? Would it be possible to add the ability to use settings as well?

**Comment by ghost** [comment]
Yes, this can definitely be done. Ideally custom editor settings should be able to be added in a generic manner. My idea would be along the lines of adding your settings to a known editor configuration key, for example `editorProps`, in either an `EditorDescriptor` or `IMetadataAware`. And then that can be spread to the editor as props.

Does that sound like it would work for you? I can create a PR with this idea shortly.

**Comment by themaf** [comment]
Yes, that should absolutely work as long as several settings can be used.

**Comment by ghost** [comment]
I've put up a PR with a fix. Let me know if the approach works for you, or if you have any comments, and I will merge and release.
